name: My first reusable action

description: "Reusable action"

inputs:
    my-input:
        type: string
        required: true
outputs:
    my-output: 
        description: "The mutated my-input as output"
        value: ${{ steps.mutate-input.outputs.OUT }}

runs:
    using: "composite"
    steps:
        - name: return version
          id: mutate-input
          shell: bash
          run: |
            dynamicOutput="`cat ./publish/output.txt`"
            echo "OUT=*** ${{ inputs.my-input }} *** mutated - $dynamicOutput" >> $GITHUB_OUTPUT