name: Test workflow

on:
    push:

jobs:
    my-job:
        name: 'Test Job'
        runs-on: ubuntu-latest
        
        steps:

            - name: Checkout source
              uses: actions/checkout@v4

            - name: Call composite action
              id: composite-action
              uses: ./.github/actions/my-first-action
              with:
                my-input: 'Hello World'

            - name: Print composite action output
              run: |
                echo "Result: '${{ steps.composite-action.outputs.my-output }}'"

            - name: 'Create notice message'
              env:
                NOTICE: "### Artifacts\nWill this even work?<br/>That would be really cool!"
              run: |
                echo "${{ env.NOTICE }}" >> $GITHUB_STEP_SUMMARY